version: '3.5'
services:
    millionaire_game1:
      image: millionaire_game_image23556533442
      build: .
      ports: 
        - '4200:4200'
      command: ng serve --host 0.0.0.0
      volumes:
        - ./:/app
