export const QUESTIONS_COGNITIVE = [
    ['Rola "policji mózgowej" w ośrodkowych układzie nerwowym należy do:', ['oligodendrocytów', 'astrocytów', 'mikrogleju', 'komórek ependymy'], 'c'],
    ['Zmienna zdychotomizowana to zmienna:', ['jednowartościowa', 'dwuwartościowa', 'trójwartościowa', 'wielowartościowa'], 'b'],
    ['Niezrozumiała i niewyraźna mowa oraz osłabienie mięśni w gardle i języku są charakterystyczne dla:', ['dysartrii', 'dystonii', 'ataksji', 'agnozji słuchowej'], 'a'],
    ['Język bułgarski jest językiem:', ['germańskim', 'romańskim', 'celtyckim', 'słowiańskim'], 'd'],
    ['Ciężka depresja i bezsenność są związane z:', ['zwiększeniem aktywności noradrenaliny', 'wysokim stężeniem 5-HT', 'blokowaniem syntezy serotoniny', 'niskim poziomem acetylocholiny'], 'c'],
    ['Predykaty, nazwy indywidualne i symbole funkcyjne danego języka pierwszego rzędu to:', ['stałe logiczne', 'stałe pozalogiczne', 'formuły atomowe', 'literały'], 'b'],
    ['Ile jest par nerwów czaszkowych?', ['11', '12', '18', '31'], 'b'],
    ['Test Fałszywych Przekonań to test sprawdzający:', ['funkcjonowanie heurystyk Nielsena', 'mentalizację', 'funkcjonowanie pamięci roboczej', 'akcelerację rozwojową'], 'b'],
    ['Hormonem przysadki mózgowej nie jest:', ['prolaktyna', 'somatostatyna', 'wazopresyna', 'hormon wzrostu'], 'b'],
    ['Schemat aktu komunikacji między nadawcą a odbiorcą zaprezentował:', ['Jacobson', 'Grice', 'Austin ', 'Milewski'], 'a'],
    ['Do aminokwasów zaliczamy:', ['endorfinę', 'acetylocholinę', 'glutaminian', 'serotoninę'], 'c'],
    ['Prawo  mówiące o tym, że liczba tranzystorów w układzie elektronicznym podwaja się co 18-24 miesiące to:', ['prawo Moorea', 'zasada Deep Blue', 'prawo Fouriera', 'aliasing'], 'a'], ['Układ nerwowy rozwija się z:', ['cewy nerwowej', 'ektodermy', 'płytki nerwowej', 'pęcherzyków wtórnych'], 'b'], ['Retardacja rozwoju to jego:', ['prawidłowy przebieg', 'opóźnienie', 'przyspieszenie', 'zatrzymanie'], 'b'],
    ['Do triady objawów zaburzenia czynności móżdżku nie należy:', ['ataksja', 'zaburzenie równowagi', 'bradykinezja', 'obniżenie napięcia mięśniowego'], 'c'],
    ['Przepis na rozwiązanie jakiegoś problemu to:', ['aksjomat', 'algorytm', 'teza', 'model'], 'b'],
    ['Pola Brodmana dotyczące budowy mózgu liczą:', ['37 obszarów', '44 obszary', '47 obszarów', '49 obszarów'], 'c'],
    ['Autorem koncepcji natury ludzkiej, która mówi o ludności jako o wilczej hordzie agresywnej wobec siebie nawzajem jest:', ['Lorenz', 'Darwin', 'Hobbes', 'Freud'], 'c'],
    ['Nie jest „prawdziwym” nerwem czaszkowym, lecz pęczkiem istoty białej międzymózgowia – to opis nerwu:', ['węchowego', 'wzrokowego', 'błędnego', 'twarzowego'], 'b'], ['Intencjonalność w koncepcji Millikan to ujęcie:', ['fizykalne', 'eliminatywistyczne', 'teleofunkcjonalistyczne', 'funkcjonalistyczne'], 'c'],
    ['Do zakończeń nerwowych otorbionych nie należą:', ['ciałka Merkela', 'ciałka Vatera-Paciniego', 'ciałka Ruffiniego', 'ciałka Meissnera'], 'a'],
    ['Klasyczna definicja prawdy mówi, że prawda to:', ['naczelna wartość do oceniania', 'zgodność myśli z rzeczywistością', 'nadrzędny cel ludzkich dążeń', 'logicznie spójny system przekonań'], 'b'],
    ['Najbardziej zewnętrzną warstwą kory mózgowej jest:', ['warstwa drobinowa', 'warstwa piramidowa', 'warstwa ziarnista', 'istota biała'], 'a'],
    ['Sufiks to termin w lingwistyce określający:', ['przedrostek', 'przyrostek', 'okołorostek', 'wrostek'], 'b'],
    ['Kwas gamma-aminomasłowy to:', ['serotonina', 'glutaminian', 'acetylocholina', 'GABA'], 'd'],
    ['Bipedalizm to:', ['dymorfizm płciowy', 'oburęczność', 'istnienie dwóch półkul mózgowych', 'dwunożność'], 'd'],
    ['Mierzeniem zużycia glukozy i tlenu przez neurony zajmuje się:', ['fMRI', 'EEG', 'PET', 'NIRS'], 'c'],
    ['Posłużenie się nazwą jakiegoś przedmiotu lub zjawiska, pozostającą z inną nazwą w pewnej relacji pozajęzykowej i zastępującą ją to:', ['homonimia', 'metonimia', 'enantiosemia', 'metafora'], 'b'],
    ['Integracją ruchu i wzroku zajmuje się płat:', ['potyliczny', 'czołowy', 'ciemieniowy', 'skroniowy'], 'c'],
    ['Bustrofedon to nazwa określająca pismo:', ['od lewej do prawej', 'od prawej do lewej', 'naprzemienne od prawej do lewej i od lewej do prawej', 'z góry na dół'], 'c'],
    ['Agnezja ciała modzelowatego to jego:', ['przerost', 'brak', 'zmniejszenie objętości', 'nieaktywność'], 'b'],
    ['Koncepcja, według której strona wykonana zgodnie z jej zasadami jest zoptymalizowana oraz dostępna bez względu na rozmiar urządzenia, na którym jest wyświetlana to:', ['Flat Design', 'Responsive Web Design', 'skeudomorfizm', 'Mobile First Approach'], 'b'],
    ['Zasada mówiąca, że zbiory A oraz B są identyczne wtw mają one dokładnie te same elementy to:', ['zasada ekstensjonalności', 'zasada dystrybutywności', 'zasada rozłączności', 'zasada równoliczności'], 'a'],
    ['Twórcą metody stawiania i krytyki hipotez był:', ['Ajdukiewicz', 'Kotarbiński', 'Popper', 'Kuhn'], 'c'],
    ['Wewnątrzkomórkowa waluta energii to:', ['HPA', 'ATP', 'AMPA', 'PMR'], 'b'],
    ['Grupa kolektywnie przypomina sobie mniej elementów niż przypominają sobie łącznie jej członkowie, kiedy wykonują zadanie pamięciowe indywidualnie – to opis:', ['efektu wachlarza', 'zjawiska zapominanie w wyniku grupowego przypominania', 'zjawiska utrudnienia wydobycia przez „podpowiedzenie” części elementów', 'zjawiska „mam to na końcu języka"'], 'b'],
    ['Proces powielania neuronów i komórek glejowych to:', ['neurogeneza', 'cytogeneza ', 'histogeneza', 'filogeneza'], 'b'],
    ['Gdy mamy dwie zmienne interwałowe, najlepszym współczynnikiem korelacji będzie:', ['r Pearsona', 'r Spearmana', 'fi Yula', 'V Kramera'], 'a'],
    ['Według danych z 2016 roku, na świecie używa się:', ['ponad 110 języków', 'mniej niż 2 tysiące języków', 'około 6 tysięcy języków', 'ponad 9 tysięcy języków'], 'c'],
    ['Co jest prawdą o pręcikach w siatkówce?', ['odpowiadają za widzenie nocne', 'są wrażliwe na kolory', 'niska czułość na światło', 'odpowiadają za widzenie dzienne'], 'a'],
    ['Semantyczny odpowiednik operacji konsekwencji logicznej to:', ['wynikanie logiczne', 'derywacja', 'dowód', 'dziedziczenie prawdziwości'], 'a'],
    ['Agnozja dotykowa to inaczej:', ['somatognozja', 'astereognozja', 'prozopagnozja', 'agnozja asocjacyjna'], 'b'],
    ['Miarą dyspersji nie jest:', ['odchylenie standardowe', 'rozstęp', 'mediana', 'kurtoza'], 'c'],
    ['Substancja blokująca receptor to jego:', ['agonista', 'polimeraza', 'antagonista', 'terminator'], 'c'],
    ['Psycholog, który wprowadził pojęcie ilorazu inteligencji to:', ['Alfred Binet', 'Wiliam Stern', 'Francis Galton', 'Charles Spearman'], 'b'],
    ['Autorem dwuczynnikowej teorii inteligencji jest:', ['Charles Spearman', 'Lewis Terman', 'Daniel Hebb', 'Philip Vernon'], 'a'],
    ['Zjawisko przyrastania wyników w testach inteligencji wraz z upływem czasu, o ok. 0,3 punktu rocznie lub trzech punktów w ciągu dekady, głównie w testach inteligencji płynnej i u osób o niskim poziomie inteligencji, to:', ['Efekt wachlarza', 'Prawo Wechslera', 'Zasada Gardnera-Guilforda', 'Efekt Flynna'], 'd'],
    ['Do autorów hierarchicznych modeli inteligencji nie należy:', ['Spearman', 'Thurstone', 'Cattell', 'Vernon'], 'b'],
    ['Konsument kupuje drogi towar, który ma swój tańszy, ale dorównujący jakością odpowiednik - w psychologii konsumenckiej zjawisko to nosi nazwę:', ['Efekt Lamborghini', 'Efekt Sennheisera', 'Efekt Apple', 'Efekt Calvina Kleina'], 'b'],
    ['Satysfakcja z zakupu produktów, na które nie wiele osób stać oraz utrata zainteresowania tymi przedmiotami, gdy inni też zaczynają je kupować, to:', ['Efekt snoba', 'Efekt owczego pędu', 'Efekt pawiego ogona', 'Efekt masowego luksusu'], 'a'],
    ['Rozważania nad neuronalnymi korelatami świadomości i wskazanie przedmóża jako siedlisko świadomości to obszar działalności:', ['Cricka i Kocha', 'Husserla', 'Ramachandrana i Hirsteina', 'McGuina'], 'a'],
    ['Rozpoznawalne, jakościowe cechy tego, co dane, które mogą powtarzać się w różnych przeżyciach doznaniowych i dlatego są pewnym typem uniwersaliów to:', ['neuronalne korelaty świadomości', 'potencjały gotowości', 'umysły franklinowskie', 'qualia'], 'd'],
    ['Julian Jaynes jest autorem koncepcji:', ['wieży generowania i testowania', 'qualiów', 'dwuizbowego umysłu', 'neuronalnych korelatów świadomości'], 'c'],
    ['Do nieprawidłowości neuroanatomicznych zaobserwowanych u osób z autyzmem nie zaliczmy:', ['zwiększonej objętość płata ciemieniowego', 'zmniejszenia tylnej części ciała modzelowatego', 'zwiększonej gęstości upakowania komórek w systemie limbicznym', 'ubytku neuronów w móżdżku'], 'a'],
    ['Jeżeli w trakcie zadania na rozpoznawanie emocji u badanego widać aktywność w korze oczodołowej, to znaczy, że rozpoznawaną emocją jest:', ['strach', 'wstręt', 'gniew', 'smutek'], 'c'],
    ['Do czterech głównych maksym konwersacyjnych, które wyróżnił Grice, nie zalicza się maksyma:', ['jakości', 'kooperacji', 'ilości', 'odpowiedniości'], 'b'],
    ['Osoby z autyzmem charakteryzuje słaba centralna koherencja, a to znaczy, że:', ['ich przetwarzanie nie jest skoncentrowane na szczególe', 'mają tendencję do przetwarzania raczej globalnej niż lokalnej informacji', 'są niezdolne do przetwarzania napływających bodźców w kontekście', 'bardziej dostrzegają i pamiętają konfigurację bodźców niż ich cechy'], 'c'],
    ['Co nie jest medycznym objawem zespołu Williamsa?', ['opóźniony rozwój motoryczny', 'opóźnione starzenie się', 'charakterystyczne rysy twarzy przypominające baśniowych elfów', 'przejściowa dziecięca hiperkalcemia'], 'b'],
    ['Przymus wykonywania wulgarnych gestów u osób z zespołem Touretta to:', ['echolalia', 'kopropraksja', 'echopraksja', 'palilalia'], 'b'],
    ['Jaki procent dzieci z autyzmem pozytywnie przechodzi test fałszywych przekonań?', ['około 5%', 'około 10%', 'około 15%', 'około 20%'], 'd'],
    ['Do zmian neuroanatomicznych u osób z ADHD nie należy:', ['zmniejszenie jądra ogoniastego w lewej półkuli', 'zmniejszenie robaka w móżdżku', 'zmniejszenie okolicy czołowej w prawej półkuli', 'zwiększenie ciała modzelowatego'], 'd'],
  ]
;
