export const STRINGS = {
  0: 'Witamy w specjalnym wydaniu Milionerów! Wybierz wersję gry, wpisz swoje imię i zaczynamy!',
  1: 'Dobrze. Jaka jest Twoja decyzja?',
  2: 'Wybrałeś Pół na pół. Prosimy komputer o odrzucenie losowo dwóch błędnych odpowiedzi:',
  3: 'Wybrałeś Telefon do przyjaciela. Zatem dzwonimy!',
  4: 'Witaj, {{ random_name }}! {{ name.capitalize()) }} gra właśnie o  {{ MONEY[i]) }} zł i potrzebuje Twojej pomocy.',
  5: 'Znasz już pytanie. Oczekujemy na Twoją odpowiedź!',
  6: '{{ andom_name.upper }}: Dobrze, postaram się pomóc.',
  7: '{{ random_name.upper }}": Hmmm...',
  8: 'Chyba znam poprawną odpowiedź na to pytanie. Według mnie jest to odpowiedź',
  9: 'Na szczęście wiem, jak Ci pomóc. Prawidłowa odpowiedź to',
  10: 'Ha! To akurat pamiętam ze studiów! To na pewno',
  11: 'To był jeden z niewielu wykładów, które pamiętam. Odpowiedź to',
  12: 'Nie mam pewności co do odpowiedzi na to pytanie. Obstawiam odpowiedź',
  13: 'Kurczę, wybacz mi, ale nie pamiętam tego dokładnie. Ale coś kojarzę, że to będzie',
  14: 'Oh! Akurat na tych zajęciach mnie nie było... Ale może zaznacz',
  15: 'Wstyd się przyznać, ale nie mam pewności. Ale raczej odpowiedź to',
  16: 'Dobrze. Jaka jest Twoja decyzja, {{ name.capitalize()) }}?',
  17: 'A więc prosimy o pomoc Publiczność w studiu!',
  18: 'Głosy publiczności rozkładają się następująco:',
  19: 'Dobrze, {{ name.capitalize()) }}. Jaka jest Twoja decyzja?',
  20: 'Hmmm...',
  21: 'O kurczę...',
  22: 'Ej, coś mi to mówi...',
  23: 'Aby zostać Milionerem, musisz odpowiedzieć na 12 pytań. Każde jest warte określoną kwotę pieniędzy.',
  24: 'Pytania o numerach 3 i 7 to pytania, na które odpowiedź daje Ci sumę gwarantowaną.',
  25: 'Do każdego pytania otrzymasz 4 warianty odpowiedzi, ale tylko jedna z nich jest poprawna.',
  26: 'W dowolnym momencie programu możesz się wycofać i zatrzymać dotychczas zdobyte pieniądze.',
  27: 'Do dyspozycji masz 3 koła ratunkowe: Pytanie do publiczności, Pół na pół oraz Telefon do przyjaciela.',
  28: 'Chyba już wszystko wiadomo. Czas rozpocząć walkę o milion złotych!',

};
